---
title: "CV"
toc: false
---

# Education

**University of Costa Rica**, San Pedro de Montes de Oca, San José \| 2020 to 2024

Candidate for B.S. in Statistics (GPA: 3.33/4.0, estimate)

------------------------------------------------------------------------

# Experience

**Anker Research Institute**, New York, NYC \| September 2024 to Present

*Junior Research*

-   Estimated the cost of a decent living standard for workers and families using the Anker Methodology across Costa Rica, Indonesia, Malawi, and rural Tanzania, supporting wage-setting policies and improving global living conditions.

-   Developed global reference values for living incomes and wages and conducted income risk assessments in rural Tanzania, comparing the applicability of the pre-existing reference value for the regions of Shinyanga and Tabora to assess regional disparities.


**Center for Research in Pure and Applied Mathematics (CIMPA)**, University of Costa Rica, San José, Costa Rica	| September 2024 to Present 

*Undergraduate Researcher*

-   Project name: ["The impact of social determinants on the spread of infectious diseases"](https://vinv.ucr.ac.cr/sigpro/web/projects/C3190) (Principal investigator: Fabio Sánchez Peña, PhD). 

-   Applied statistical techniques in R to analyze data from GLOBE-NASA, Costa Rican Ministry of Public Health, and other sources on mosquito habitats and transmission vectors. 

-   Ensured data integrity and consistency across diverse sources to support accurate modeling of environmental conditions and the prevalence of breeding sites.

