project:
  type: website 
  output-dir: docs

website:
  title: "Iván Daniel Rodríguez Cruz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: litera
      dark: litera
    css: styles.css
    toc: true

editor: visual

