project:
  type: website 
  output-dir: docs 

# Aquí se buscan los "icon" para poner: https://icons.getbootstrap.com/
website:
  title: "Iván Daniel Rodríguez Cruz"
  page-navigation: true
  twitter-card: true
  cookie-consent: 
     palette: light  
     style: headline
     type: implied
  open-graph:
    locale: es_ES
    site-name: Quarto
    
    
  # Opciones para la barra de navegación:  
  navbar:
    title: "Iván Daniel Rodríguez Cruz" 
    back-to-top-navigation: false # Dejar fija la barra de navegación.
    background: "#182A48" # Color de la barra de navegación; color azul de Google.
    #foreground: "light" # Color del texto en la barra de navegación.
    search: true 
    position: fixed   
    pinned: true 
    right:
      - icon: linkedin 
        href: https://www.linkedin.com/in/iv%C3%A1n-daniel-rodr%C3%ADguez-cruz-2471a325a/
      - icon: github
        href: https://github.com/ivanrodc
    left:
      - href: index.qmd
        text: Home
      - documentos/personal/CV.qmd
      - documentos/personal/contact.qmd

  page-footer:
    border: false
    background: light
    left: "{{< bi c-circle size=1em >}} 2024 Iván Daniel Rodríguez Cruz" 
    right: 
      - text: "This website is built with {{< bi heart-fill size=1em >}}, {{< bi github size=1em >}}, R and Quarto"
        href: https://quarto.org/

format:
  html:
    theme: 
      light: flatly
    css: styles.css
    linkcolor: "#3081D0" # hyperlink
    #toc: true

editor: visual 

